name: package

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        include:
          - python: "3.10"
            torch: 2.3.1
            torchaudio: 2.3.1
          - python: "3.14"
            torch: 2.14.0
            torchaudio: 2.11.0

    steps:
      - name: Clone
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y libsndfile1

      - name: Install
        run: make PYTHON_VERSION=${{ matrix.python }} TORCH_VERSION=${{ matrix.torch }} TORCHAUDIO_VERSION=${{ matrix.torchaudio }} PLATFORM=cpu venv tool

      - name: Check
        run: make check

      - name: Test
        run: make test-all OPT="--dtype double"

      - name: Coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
